# Generated by Django 5.1.2 on 2024-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0002_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
