# Generated by Django 5.1.2 on 2024-12-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
