# Generated by Django 5.1.2 on 2024-12-12 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0004_remove_instructorprofile_user_delete_customuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('about_me', models.TextField(blank=True)),
                ('facebook_username', models.CharField(blank=True, max_length=50)),
                ('twitter_username', models.CharField(blank=True, max_length=50)),
                ('instagram_username', models.CharField(blank=True, max_length=50)),
                ('youtube_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('courses_created', models.IntegerField(default=0)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('ratings', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
