# Generated by Django 5.1.2 on 2024-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0005_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
