# Generated by Django 5.1.2 on 2024-12-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0006_instructorprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/profile_images/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_images/'),
        ),
    ]
