# Generated by Django 5.1.2 on 2024-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0007_alter_instructorprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
