# Generated by Django 5.1.2 on 2024-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0008_instructorprofile_email_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='instructors/profile_images/default.jpg', null=True, upload_to='instructors/profile_images/'),
        ),
    ]
