# Generated by Django 5.1.2 on 2024-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0009_alter_instructorprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/profile_images/'),
        ),
    ]
