# Generated by Django 5.1.2 on 2024-12-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
