# Generated by Django 5.1.2 on 2024-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0013_lecture_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lecture',
        ),
        migrations.AddField(
            model_name='instructorclasscourse',
            name='lectures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instructorclasscourse',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
