# Generated by Django 5.1.2 on 2024-12-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0014_remove_topic_lecture_instructorclasscourse_lectures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorclasscourse',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='instructorclasscourse',
            name='topics',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lecture Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='champapp.instructorclasscourse')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Topic Name')),
                ('video_link', models.URLField(verbose_name='Video Link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('topic_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='champapp.lecture')),
            ],
        ),
    ]
