# Generated by Django 5.1.2 on 2024-12-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0015_remove_instructorclasscourse_lectures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('category', models.CharField(choices=[('Engineer', 'Engineer'), ('Medical', 'Medical'), ('Information technology', 'Information technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=50)),
                ('level', models.CharField(choices=[('All level', 'All level'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=50)),
                ('languages', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Hindi', 'Hindi')], max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('course_time', models.CharField(max_length=50)),
                ('total_lecture', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_upload', models.FileField(blank=True, null=True, upload_to='course_videos/')),
            ],
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='created_at',
            new_name='lecture_created_at',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='lecture_name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='created_at',
            new_name='topic_created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic_name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='video_link',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(blank=True, null=True, verbose_name='Topic Description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='champapp.sampleclasscourse'),
        ),
    ]
