# Generated by Django 5.1.2 on 2024-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0016_sampleclasscourse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_video_link',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=50),
        ),
    ]
