# Generated by Django 5.1.2 on 2024-12-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0017_remove_lecture_lecture_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='SampleClassCourse',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
