# Generated by Django 5.1.2 on 2024-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0019_lecture_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
