# Generated by Django 5.1.2 on 2024-12-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0020_topic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
