# Generated by Django 5.1.2 on 2024-12-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0022_course1_alter_faq_question_alter_faq_course_lecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
