# Generated by Django 5.1.2 on 2024-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0023_alter_course1_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
