# Generated by Django 5.1.2 on 2024-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0024_alter_course1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='short_description',
            field=models.TextField(default='Default short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course1',
            name='category',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Medical', 'Medical'), ('Information technology', 'Information technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=50),
        ),
    ]
