# Generated by Django 5.1.2 on 2024-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0025_course1_short_description_alter_course1_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='level',
            field=models.CharField(choices=[('All level', 'All level'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Select', max_length=50),
        ),
        migrations.AlterField(
            model_name='course1',
            name='languages',
            field=models.CharField(choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Hindi', 'Hindi')], max_length=10),
        ),
    ]
