# Generated by Django 5.1.2 on 2024-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0026_course1_level_alter_course1_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='course_time',
            field=models.CharField(default='00:00:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course1',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
