# Generated by Django 5.1.2 on 2024-12-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0027_course1_course_time_course1_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='total_lecture',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course1',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
