# Generated by Django 5.1.2 on 2024-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0029_course1_created_at_faq_created_at_lecture_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
