# Generated by Django 5.1.2 on 2024-12-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0030_topic_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
