# Generated by Django 5.1.2 on 2024-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0031_topic_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Live', 'Live'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
