# Generated by Django 5.1.2 on 2024-12-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0032_course1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course1',
            name='status',
        ),
    ]
