# Generated by Django 5.1.2 on 2024-12-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0034_course1_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course1',
            name='instructor',
        ),
    ]
