# Generated by Django 5.1.2 on 2024-12-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0038_course1_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course1',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course1',
            name='instructor',
        ),
    ]
