# Generated by Django 5.1.2 on 2024-12-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0041_alter_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
