# Generated by Django 5.1.2 on 2024-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0047_alter_course1_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Live', 'Live'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
