# Generated by Django 5.1.2 on 2024-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0049_enrolledcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
