# Generated by Django 5.1.2 on 2024-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0050_enrolledcourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='completed_topics',
            field=models.IntegerField(default=0),
        ),
    ]
