# Generated by Django 5.1.2 on 2025-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0054_profile_favorites_alter_favoritecourse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='champapp.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profile_favorites', to='champapp.course'),
        ),
    ]
