# Generated by Django 5.1.2 on 2025-01-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0056_alter_studentprofile_favorites_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
