# Generated by Django 5.1.2 on 2025-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0057_topic_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
