# Generated by Django 5.2.7 on 2025-10-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0060_alter_payment_course_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('google_adsense_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('facebook_ads_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('average_cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ad Revenues',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champapp.course1'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_platform', models.CharField(choices=[('google_adsense', 'Google AdSense'), ('facebook_ads', 'Facebook Audience Network'), ('other', 'Other')], default='google_adsense', max_length=50)),
                ('ad_unit_id', models.CharField(blank=True, max_length=100)),
                ('estimated_revenue', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('cpm_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('view_duration', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='champapp.course1')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='champapp.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_share_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('instructor_share_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('platform_share_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('minimum_watch_time', models.IntegerField(default=5)),
                ('earnings_per_minute', models.DecimalField(decimal_places=4, default=0.5, max_digits=10)),
                ('completion_bonus', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share', to='champapp.course1')),
            ],
            options={
                'verbose_name': 'Revenue Share Configuration',
                'verbose_name_plural': 'Revenue Share Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_watch_time', models.IntegerField(default=0)),
                ('total_courses_watched', models.IntegerField(default=0)),
                ('total_ad_impressions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('paytm', 'Paytm'), ('paypal', 'PayPal')], max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('user_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(choices=[('student_watch', 'Student Watch Time'), ('instructor_course', 'Instructor Course Content'), ('referral_bonus', 'Referral Bonus'), ('completion_bonus', 'Course Completion Bonus')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ad_impressions', models.ManyToManyField(blank=True, related_name='earnings', to='champapp.adimpression')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='champapp.course1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='champapp.withdrawal')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['-viewed_at'], name='champapp_ad_viewed__5fe21c_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', 'course'], name='champapp_ad_user_id_d658fd_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='champapp_wi_user_id_f461c6_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['-requested_at'], name='champapp_wi_request_7d53c6_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['user', 'status'], name='champapp_ea_user_id_c2ded7_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['-earned_at'], name='champapp_ea_earned__14f270_idx'),
        ),
    ]
