# Generated by Django 5.2.7 on 2025-10-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champapp', '0061_adrevenue_alter_payment_course_adimpression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueshare',
            name='instructor_share_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='revenueshare',
            name='platform_share_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='revenueshare',
            name='student_share_percentage',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=5),
        ),
    ]
