# Generated by Django 5.0.4 on 2024-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="betauser",
            name="address",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="betauser",
            name="degree",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="betauser",
            name="grad_year",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="betauser",
            name="job_status",
            field=models.CharField(default="", max_length=20),
        ),
    ]
