# Generated by Django 5.0.4 on 2024-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispurchased',
            name='purchased_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
