# Generated by Django 5.0.4 on 2024-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_betauser_address_betauser_degree_betauser_grad_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="betauser",
            name="profile_updated",
            field=models.BooleanField(default=False),
        ),
    ]
