# Generated by Django 5.0.3 on 2024-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_betauser_profile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.BooleanField(default=False),
        ),
    ]
