# Generated by Django 5.0.4 on 2024-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betauser',
            name='address',
        ),
        migrations.AddField(
            model_name='betauser',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='betauser',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
    ]
