# Generated by Django 5.0.4 on 2024-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_betauser_address_betauser_city_betauser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
