# Generated by Django 5.0.4 on 2024-05-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='course',
            name='purchased',
        ),
    ]
