# Generated by Django 5.0.4 on 2024-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betauser',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='static/profile_pics'),
        ),
    ]
