# Generated by Django 5.0.4 on 2024-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_betauser_profilepic_customuser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userfor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
