# Generated by Django 5.0.4 on 2024-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ispurchased',
            name='purchased_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
