# Generated by Django 5.0.4 on 2024-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_course_lectures_progress_completed_lectures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default=False, upload_to='static/course_videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Level', 'All level')], default='all', max_length=20),
        ),
    ]
