# Generated by Django 5.0.4 on 2024-05-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_course_course_rating_chatbox_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbox', to='base.chatbox')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='base.betauser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='base.betauser')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
